// DROP DE TABELAS
DROP TABLE AUTOMOVEIS CASCADE CONSTRAINTS;
DROP TABLE REVENDEDORAS CASCADE CONSTRAINTS;
DROP TABLE CONSUMIDORES CASCADE CONSTRAINTS;
DROP TABLE GARAGENS CASCADE CONSTRAINTS;
DROP TABLE NEGOCIOS CASCADE CONSTRAINTS;

// CRIACAO DE TABELAS
CREATE TABLE AUTOMOVEIS ( 
    CODIGO NUMBER(4) PRIMARY KEY,
    FABRICANTE VARCHAR2(20) NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    ANO NUMBER(4) NOT NULL,
    PAIS VARCHAR2(15) NOT NULL,
    PRECO_TABELA NUMBER(8,2) NOT NULL
);

CREATE TABLE REVENDEDORAS (
    CNPJ VARCHAR2(16) PRIMARY KEY,
    NOME VARCHAR2(20) NOT NULL,
    PROPRIETARIO VARCHAR2(20) NOT NULL,
    CIDADE VARCHAR2(15) NOT NULL,
    ESTADO CHAR(2) NOT NULL
);

CREATE TABLE CONSUMIDORES (
    ID_CON NUMBER(4) PRIMARY KEY,
    NOME VARCHAR2(20) NOT NULL,
    SOBRENOME VARCHAR2(15) NOT NULL
);

CREATE TABLE NEGOCIOS (
    ANOAUTO NUMBER(4) NOT NULL,
    DATA DATE NOT NULL,
    PRECO NUMBER(8,2) NOT NULL,
    COMPRADOR NUMBER(4) NOT NULL,
    REVENDA VARCHAR2(16) NOT NULL,
    CODAUTO NUMBER(4) NOT NULL,
    CONSTRAINT FK_CONSUMIDORES_NEGOCIOS FOREIGN KEY (COMPRADOR) REFERENCES CONSUMIDORES (ID_CON),
    CONSTRAINT FK_AUTOMOVEIS_NEGOCIOS FOREIGN KEY (CODAUTO) REFERENCES AUTOMOVEIS (CODIGO),
    CONSTRAINT FK_REVENDEDORAS_NEGOCIOS FOREIGN KEY (REVENDA) REFERENCES REVENDEDORAS (CNPJ),
    CONSTRAINT PK_NEGOCIOS PRIMARY KEY (COMPRADOR, REVENDA, CODAUTO)
);

CREATE TABLE GARAGENS (
    ANOAUTO NUMBER(4) NOT NULL,
    QUANTIDADE NUMBER(4) NOT NULL,
    CNPJREVENDA VARCHAR2(16) NOT NULL,
    CODAUTO NUMBER(4) NOT NULL,
    CONSTRAINT FK_REVENDEDORAS_GARAGENS FOREIGN KEY (CNPJREVENDA) REFERENCES REVENDEDORAS (CNPJ),
    CONSTRAINT FK_AUTOMOVEIS_GARAGENS FOREIGN KEY (CODAUTO) REFERENCES AUTOMOVEIS (CODIGO),
    CONSTRAINT PK_GARAGENS PRIMARY KEY (CNPJREVENDA, CODAUTO)
);

